Added support for unix_socket connections
PanCakeConnaisseur/user_backend_sql_raw pull request #29
Opened 2020-05-20 15:29 UTC by oucil

- updated postgresql and mariadb adapters so that they will test for supplied socket first, then fall back to standard host:port
- included config test and updated multivalue tests

2020-05-20 15:31 UTC, oucil commented
Addresses #27

2020-10-13 04:09 UTC, PanCakeConnaisseur commented
Thank you Oucil. I only now had the time to work on this. Evaluating this now.

2020-10-13 04:35 UTC, PanCakeConnaisseur requested changes
Thanks again for the PR.

2020-10-13 04:35 UTC, PanCakeConnaisseur commented on lib/Config.php
> +	const DEFAULT_DB_SOCK = NULL;
Is there nor sensible default value other than `NULL`?

2020-10-13 04:35 UTC, PanCakeConnaisseur commented on lib/Config.php
> +	const CONFIG_KEY_DB_SOCK = 'db_sock';
In the spirit of clean code, please use full words everywhere, e.g. `db_sock`-> `db_socket`.

2020-10-13 04:35 UTC, PanCakeConnaisseur commented on lib/Config.php
> +			,self::DEFAULT_DB_SOCK);
What will happen if the config parameter is empty and defaults to `NULL`, will it connect?

2020-10-13 04:35 UTC, PanCakeConnaisseur commented on lib/Dbs/Mariadb.php
> +		}
`mysql`, `dname` and `charset` could be unified. Or maybe two different functions for socket and host to avoid branching at this point.

2020-10-13 04:35 UTC, PanCakeConnaisseur commented on lib/Dbs/Mariadb.php
> +		if ($this->config->getDbSock()) {
Please use explicit !empty() because it is not obvious that an empty string evaluates to `FALSE`. This makes code easier to read and also hints that `getDbSock()` returns a string.

2020-10-13 04:35 UTC, PanCakeConnaisseur commented on lib/Dbs/Mariadb.php
> +		if ($this->config->getDbSock()) {
Also, what if both socket and host configuration are specified in the config. With this socket will win. I think host based connections are more common and should be default.

2020-10-13 04:35 UTC, PanCakeConnaisseur commented on lib/Dbs/Mariadb.php
> +			. ';dbname=' . $this->config->getDbName()
indentation (also in the other three returns)

2020-10-13 04:35 UTC, PanCakeConnaisseur commented on tests/Unit/ConfigTest.php
> -			->willReturn(array(
indentation

2021-05-28 19:23 UTC, Tachi107 commented on lib/Dbs/Mariadb.php
> +		if ($this->config->getDbSock()) {
Unix socket based connections are faster and can be more secure, and I see no reason why someone would prefer using a TCP socket when a Unix one is available

2022-01-11 23:09 UTC, Tachi107 commented on lib/Config.php
> +	const DEFAULT_DB_SOCK = NULL;
Yes, `/run/postgresql`

2022-01-12 14:36 UTC, oucil commented on lib/Config.php
> +	const DEFAULT_DB_SOCK = NULL;
@PanCakeConnaisseur @Tachi107 Honestly, I don't believe that anything should have a default pointing at 'postgresql'.  IMO, that should be left to the user to configure as a minimum requirement, and explicit exceptions should exist when they haven't been.  I'm biased though, as I've been a RHEL/Cent/Rocky linux stack for years, but it seems odd that I have to reset these values, and others can plug and play, might that not lead to confusion among 3rd party devs that are inspecting issues with someone using this when defaults are in use and they have to read your documentation to find them, rather than seeing them explicitly set?

2022-01-12 14:37 UTC, oucil commented
@PanCakeConnaisseur Been a long time, my apologies, I changed professions and haven't had a lot of time till now, thanks @Tachi107 for reminding me of this PR :)  I'll try to make the suggested updates and do some testing and resubmit.  Cheers!

2022-01-12 14:39 UTC, oucil commented on lib/Dbs/Mariadb.php
> +		if ($this->config->getDbSock()) {
Agreed @Tachi107, I believe this comes back to my comment above about confusion when you set defaults for one specific database.  I don't believe the connection should have defaults, and I think that's to avoid potential overlaps when choosing to use a socket, or forcing one set of users to set them, and another group of users to not have to.

2022-01-12 16:12 UTC, Tachi107 commented
Thanks for the renewed interest in this feature! If you'd like, I could apply this patch to my server as soon as you'll submit your changes, to give you an extra beta-tester :)

2022-01-12 16:27 UTC, Tachi107 commented on lib/Config.php
> +	const DEFAULT_DB_SOCK = NULL;
I agree, but I suggested that default to match the current behaviour of the app (that is, using postgresql by default); if you leave this to `NULL`, users with postgresql enabled on their server would use the inefficient TCP socket by default even if the unix one is available. 

A better approach, in my opinion, would be to not default to any db type, so that you always have to explicitly set `db_type` to something, and then depending on the type of db chosen the `db_socket` should have an appropriate value (e.g. `/run/postgresql` for postgres, etc), with unix sockets being the preferred connection method.

And taking a better look at the source I realized that this "default based on the db type" approach is already in place, sorry for my almost useless comments :/

2022-01-12 16:45 UTC, BigMichi1 commented on lib/Dbs/Postgresql.php
> +			return 'pgsql:unix_socket=' . $this->config->getDbSock()
I had to change unix_socket to host to make it work with postgresql

2024-04-29 23:05 UTC, PanCakeConnaisseur commented
I recently switched operating systems and the way services communicate does not involve chroots. Therefore, I looked into socket communication and it is, as you suggested, faster and easier. Easier because there is not need for passwords because services are identified by the system user that they run under.

I was about to check this PR again and implement socket support. During research I realized that socket communication works for PostgreSQL out-of-the-box. You can simply set `db_host` (which becomes `host` in the DSN) to the path of the socket and it just works - as many things in PostgreSQL as opposed to MySQL.

I am not sure if its worth the effort to implement this just for MySQL. Its the time needed to do this cleanly (there was no further commits in this PR) and would also complicate the configuration.

I'll leave this open for a while to give people the opportunity to express how much they need this in MySQL. I am leaning towards [not putting any effort into MySQL](https://github.com/PanCakeConnaisseur/user_backend_sql_raw/issues/46#issuecomment-2081741993).

2024-05-02 20:07 UTC, oucil commented
Glad you see the benefit of the socket connections, though it's disappointing to see the reason you plan to forego support for other systems is because your PostgresSQL works out of the box.

This shouldn't be a MySQL vs PostgresSQL debate, there are pros and cons to each and other peoples choices are valid. If you want it to be about that though, [Nextcloud recommends MySQL/MariaDB](https://docs.nextcloud.com/server/latest/admin_manual/installation/installation_wizard.html#database-choice) as their preferred choice, but also support Oracle 11g, and PostgreSQL. It doesn't make any sense that you would forego support for the recommended solution and DB behind most Nextcloud installations.

If this is a personal project that you're just sharing for fun, then thank you for doing that, the code base is good and we appreciate it! But if this is meant to grow, saying no to three other systems because yours works without any work is a bit short sighted.

Like I said, I do appreciate your work.
Thanks.

2024-05-03 16:54 UTC, alexeyabel commented
@oucil,I started another (private) branch in the meantime to unify the db configuration using DSNs, which would also enable the use of much more DBs and keep support for MySQL. Its in progress, so please don't work on this PR anymore. Release will be soonish, in 1-21 days.

Regarding PostgreSQL vs MySQL: Nextcloud recommends MySQL but there is no reason given. A few years ago I asked in the official discourse forum and no answer was provided. I can only assume that this sentence hasn't been changed in the documentation for 10 years and nobody cared to do so. In my job experience PostgreSQL dominates, too. With my experience using MySQL I can totally understand why. But again, I don't claim to an expert on the subject.

2024-05-03 16:54 UTC, closed without merging

2024-05-03 17:06 UTC, oucil commented
@PanCakeConnaisseur That's great to hear, and like I said, I really do appreciate your work on this. Sounds like a great solution!